{ pkgs, lib, ... }:
{
  networking.hostName = "bes";

  # Boot and ZRAM swap settings
  boot.tmp.cleanOnBoot = true;
  zramSwap = {
    enable = true;
    memoryPercent = 100;
  };

  # Host-specific firewall settings
  networking.firewall = {
    trustedInterfaces = [ "tailscale0" ];
    allowedTCPPorts = [ 80 443 853 ];
    allowedUDPPorts = [ 853 ];
  };
  networking.nftables.enable = true;


  # Allow the adguardhome user to read the certificates generated by ACME/Caddy
  users.users.adguardhome = {
    isSystemUser = true;
    group = "adguardhome";
    extraGroups = [ "acme" ];
  };
  users.groups.adguardhome = {};

  # Allow caddy to read/traverse /data
  users.users.caddy.extraGroups = [ "shared-data" ];


  # ACME (Let's Encrypt) Configuration
  security.acme = {
    acceptTerms = true;
    defaults.email = "letsencrypt@lennihein.com";

    certs."dns.lostinthe.cloud" = {
      domain = "dns.lostinthe.cloud";
      extraDomainNames = [ "*.dns.lostinthe.cloud" ];
      dnsProvider = "cloudflare";
      credentialFiles = {
        "CF_DNS_API_TOKEN_FILE" = "/var/lib/secrets/cloudflare-api-token";
      };
      postRun = "systemctl restart adguardhome.service";
      group = "acme";
    };
  };

  # Caddy web server reverse proxy
  services.caddy = {
    enable = true;
    extraConfig = ''
      (forward_auth) {
          forward_auth localhost:9091 {
              uri /api/authz/forward-auth?authelia_url=https://auth.bes.lennihein.com
              copy_headers Remote-User Remote-Groups Remote-Name Remote-Email
          }
      }

      auth.bes.lennihein.com {
          reverse_proxy localhost:9091
      }

      vpn.bes.lostinthe.cloud {
          reverse_proxy localhost:3001
      }

      adguard.bes.lostinthe.cloud {
          reverse_proxy http://127.0.0.1:3000
      }

      dns.lostinthe.cloud {
          respond "try TLS or QUICK..."
      }

      git.lennihein.com {
          reverse_proxy localhost:3002
      }

      data.bes.lennihein.com {
          import forward_auth
          reverse_proxy localhost:3003
      }

      terminal.bes.lennihein.com {
          import forward_auth
          reverse_proxy localhost:7681
      }

      share.bes.lennihein.com {
          reverse_proxy localhost:3004
      }

      www.bes.lennihein.com {
          root * /data/http
          file_server
      }
    '';
  };

  services.ttyd = {
    enable = true;
    interface = "127.0.0.1";
    port = 7681;
    writeable = true;
    entrypoint = [ "${pkgs.shadow}/bin/login" "-f" "lenni" ];
    clientOptions = {
      theme = ''{"background": "#282a36", "foreground": "#f8f8f2", "cursor": "#f8f8f2", "selectionBackground": "#44475a", "black": "#21222c", "red": "#ff5555", "green": "#50fa7b", "yellow": "#f1fa8c", "blue": "#bd93f9", "magenta": "#ff79c6", "cyan": "#8be9fd", "white": "#bfbfbf", "brightBlack": "#6272a4", "brightRed": "#ff6e6e", "brightGreen": "#69ff94", "brightYellow": "#ffffa5", "brightBlue": "#d6acff", "brightMagenta": "#ff92df", "brightCyan": "#a4ffff", "brightWhite": "#ffffff"}'';
    };
  };

  systemd.tmpfiles.rules = [
    "d /data/http 2770 caddy shared-data - -"
  ];

  system.stateVersion = lib.mkForce "23.11";
}

