{ pkgs, lib, ... }:
{
  networking.hostName = "bes";

  # Boot and ZRAM swap settings
  boot.tmp.cleanOnBoot = true;
  zramSwap = {
    enable = true;
    memoryPercent = 100;
  };

  # Host-specific firewall settings
  networking.firewall = {
    trustedInterfaces = [ "tailscale0" ];
    allowedTCPPorts = [ 80 443 853 ];
    allowedUDPPorts = [ 853 ];
  };
  networking.nftables.enable = true;


  # Allow the adguardhome user to read the certificates generated by ACME/Caddy
  users.users.adguardhome = {
    isSystemUser = true;
    group = "adguardhome";
    extraGroups = [ "acme" ];
  };
  users.groups.adguardhome = {};

  # Allow caddy to read/traverse /data
  users.users.caddy.extraGroups = [ "shared-data" ];


  # ACME (Let's Encrypt) Configuration
  security.acme = {
    acceptTerms = true;
    defaults.email = "letsencrypt@lennihein.com";

    certs."dns.lostinthe.cloud" = {
      domain = "dns.lostinthe.cloud";
      extraDomainNames = [ "*.dns.lostinthe.cloud" ];
      dnsProvider = "cloudflare";
      credentialFiles = {
        "CF_DNS_API_TOKEN_FILE" = "/var/lib/secrets/cloudflare-api-token";
      };
      postRun = "systemctl restart adguardhome.service";
      group = "acme";
    };
  };

  # Caddy web server reverse proxy
  services.caddy = {
    enable = true;
    extraConfig = ''
      (forward_auth) {
          forward_auth localhost:9091 {
              uri /api/authz/forward-auth?authelia_url=https://auth.bes.lennihein.com
              copy_headers Remote-User Remote-Groups Remote-Name Remote-Email
          }
      }

      auth.bes.lennihein.com {
          reverse_proxy localhost:9091
      }

      vpn.bes.lostinthe.cloud {
          reverse_proxy localhost:3001
      }

      adguard.bes.lostinthe.cloud {
          reverse_proxy http://127.0.0.1:3000
      }

      dns.lostinthe.cloud {
          respond "try TLS or QUICK..."
      }

      git.lennihein.com {
          reverse_proxy localhost:3002
      }

      data.bes.lennihein.com {
          import forward_auth
          reverse_proxy localhost:3003
      }

      terminal.bes.lennihein.com {
          import forward_auth
          reverse_proxy localhost:7681
      }

      terminal-seth.bes.lennihein.com {
          import forward_auth
          reverse_proxy seth.lennihein.com:7681
      }

      terminal-sobek.bes.lennihein.com {
          import forward_auth
          reverse_proxy sobek.lennihein.com:7681
      }

      headplane.bes.lennihein.com {
          import forward_auth
          redir / /admin/ 302
          reverse_proxy localhost:3005
      }

      share.bes.lennihein.com {
          reverse_proxy localhost:3004
      }

      www.bes.lennihein.com, bes.lennihein.com {
          root * /data/http
          file_server
      }
    '';
  };

  systemd.tmpfiles.rules = [
    "d /data/http 2770 caddy shared-data - -"
  ];

  system.activationScripts.besLandingPage.text = ''
    mkdir -p /data/http
    cp -f ${./http/index.html} /data/http/index.html
    cp -f ${./http/bes.png} /data/http/bes.png
    chown caddy:shared-data /data/http/index.html /data/http/bes.png
    chmod 644 /data/http/index.html /data/http/bes.png
  '';

  system.stateVersion = lib.mkForce "23.11";
}

