# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "thunderbolt" "nvme" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-401b6787-2f3d-4df4-99f3-6ea6ca3d7f64";
      fsType = "btrfs";
    };

  boot.initrd.luks.devices."luks-401b6787-2f3d-4df4-99f3-6ea6ca3d7f64".device = "/dev/disk/by-uuid/401b6787-2f3d-4df4-99f3-6ea6ca3d7f64";

  fileSystems."/home" =
    { device = "/dev/mapper/luks-401b6787-2f3d-4df4-99f3-6ea6ca3d7f64";
      fsType = "btrfs";
      options = [ "subvol=home" ];
    };

  fileSystems."/nix" =
    { device = "/dev/mapper/luks-401b6787-2f3d-4df4-99f3-6ea6ca3d7f64";
      fsType = "btrfs";
      options = [ "subvol=nix" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/B020-7E8D";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/mapper/luks-08708d76-a569-45c6-b123-9d74c6ecc1e8"; }
    ];

  boot.initrd.luks.devices."luks-08708d76-a569-45c6-b123-9d74c6ecc1e8".device = "/dev/disk/by-uuid/08708d76-a569-45c6-b123-9d74c6ecc1e8";

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
